# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details test
#
defaults: &defaults
  working_directory: /tmp/ffv2
  docker:
    - image: circleci/node:8
  
version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Install Deps
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace: 
          root: /tmp
          paths:
            - ffv2
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Build Project
          command: yarn run build
      - persist_to_workspace: 
          root: /tmp
          paths:
            - ffv2
  build_for_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run: 
          name: Build project for deploy
          command: DEPLOY_ENV=prod yarn run build
  deploy_to_prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run: 
          name: Switch firebase project to prod
          command: ./node_modules/.bin/firebase use prod
      - run: 
          name: Deploy to Firebase (Production)
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting
  deploy_to_dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Switch firebase project to dev
          command: ./node_modules/.bin/firebase use dev
      - run:
          name: Deploy to Firebase (Dev)
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - dev
                - master
      - build:
          requires: 
            - install_dependencies
          filters:
            branches:
              only:
                - dev
      - deploy_to_dev:
          requires:
            - install_dependencies
            - build
          filters:
            branches:
              only:
                - dev
      - build_for_production:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - master
      - deploy_to_prod:
          requires: 
            - install_dependencies
            - build_for_production
          filters:
            branches:
              only:
                - master
  test-build:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - /renovate.*/
      - build:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - /renovate.*/
